blogster/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('',
    
    # GENERIC
    url(r'^lookup/obj/$', 'grappelli.views.generic.generic_lookup', name="grp_generic_lookup"),
    # FOREIGNKEY LOOKUP
    url(r'^lookup/related/$', 'grappelli.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^lookup/m2m/$', 'grappelli.views.related.m2m_lookup', name="grp_m2m_lookup"),
    
)

blogster/urls.py
# -*- coding: utf-8-*-
import os, sys
from django.conf.urls.defaults import *
from blogster.grappelli.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
from blogster.blogs.views import *
from blogster.portfolyo.views import *
from blogster.anasayfa.views import *


#dersfeeds = {'latest': Blogss,}


from blogster.iletisim.views import *
KlasorYolu = os.path.dirname(__file__)
urlpatterns = patterns('',
    (r'^$', anasayfa),
    (r'^admin/filebrowser/', include('filebrowser.urls')),
    (r'^portfolyo/$', portfolyo),
    (r'^anasayfa/$', anasayfa),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^blogs/$', blogs),
    (r'^blogsrss/$', blogsrss),
    (r'^arsivblogs/$', blogsarsiv),
    (r'^blogs/([\w\-]+)/$', detay),
    (r'^siparis/gonderildi/', 'blogster.siparis.views.gonderildi'),
    (r'^siparis/','blogster.siparis.views.siparisonsayfa'),
    (r'^iletisim/gonderildi/', 'blogster.iletisim.views.gonderildi'),
    (r'^iletisim/','blogster.iletisim.views.iletisimonsayfa'),
    (r'^admin/(.*)', admin.site.root),
    (r'^grappelli/', include('grappelli.urls')),
    #(r'^feeds/rss/$', RssBlogsFeed()),
   # (r'^feeds/atom/$', AtomBlogsFeed()),
  #  (r'^dersfeeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': dersfeeds}),
    (r'^robots.txt$', 'django.views.generic.simple.direct_to_template', { 'template': 'robots.txt' }, 'index'),
    (r'^sitemap.xml$', 'django.views.generic.simple.direct_to_template', { 'template': 'sitemap.xml' }, 'index'),
    (r'^ttk_internet_sitesi$', 'django.views.generic.simple.direct_to_template', { 'template': 'ttk_internet_sitesi.htm' }, 'index'),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(KlasorYolu, "static/")}),
)

blogster/anasayfa/models.py
# -*- coding: utf-8-*-

from django.db import models
from datetime import datetime

class Anasayfa(models.Model):
    konu = models.CharField(max_length=100, verbose_name="Konu")
    icerik = models.TextField(max_length=1000, verbose_name="İçerik")
    tarih = models.DateTimeField(verbose_name="Yayın Tarihi", default=datetime.now)
    
    
    def __unicode__(self):
        return self.konu
        return self.icerik

    class Meta:
        verbose_name_plural = "Anasayfa"
    
    

blogster/blogs/models.py
# -*- coding: utf-8-*-

from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Blogs(models.Model):
    konu = models.CharField(max_length=100, verbose_name="Konu")
    slug = models.SlugField(max_length=300, help_text='Max: 300 Karakter')
    user = models.ForeignKey(User,verbose_name="Ekleyen")
    icerikozet = models.TextField(max_length=250, verbose_name="İçerik Özeti")
    icerik = models.TextField(max_length=1000, verbose_name="İçerik")
    tarih = models.DateTimeField(verbose_name="Yayın Tarihi", default=datetime.now)
    yayinda = models.BooleanField(verbose_name="Yayınla")
    arsiv = models.BooleanField(verbose_name="Arşivle")
    
   
    def __unicode__(self):
        return self.konu
        return self.icerik
        return self.icerikozet

    class Meta:
        verbose_name_plural = "Blog"


class Yorum(models.Model):
    konu = models.ForeignKey(Blogs)
    isim = models.CharField(max_length=100, verbose_name="İsim")
    email = models.CharField(max_length=100, verbose_name="E Mail")
    mesaj = models.TextField(max_length=500, verbose_name="İçerik")
    ip = models.TextField(max_length=20)
    smd5 = models.TextField(max_length=500)
    tarih = models.DateTimeField(auto_now_add=True)
    
    
   
    def __unicode__(self):
        return self.mesaj


    class Meta:
        verbose_name_plural = "Yorum"


    
    

blogster/blogs/forms.py
# -*- coding: utf-8-*-
from django.forms import ModelForm
from blogster.blogs.models import Yorum

class Formu(ModelForm):
	def __init__(self, data=None, *args, **kwargs):
		if data=={}:
			data=None
		ModelForm.__init__(self, data, *args, **kwargs)
	class Meta:
		model = Yorum

blogster/anasayfa/views.py
# -*- coding: utf-8-*-

# Create your views here.
from blogster.anasayfa.models import Anasayfa
from django.shortcuts import render_to_response

def anasayfa(request):
    kayitlarana = Anasayfa.objects.all()
    return render_to_response("anasayfa.html", {'kayitlarana':kayitlarana})
    

blogster/blogs/views.py
# -*- coding: utf-8-*-

# Create your views here
from blogster.blogs.models import Blogs, Yorum
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db.models import Q
from blogster.blogs.forms import Formu
from django.http import HttpResponseRedirect


def blogs(request):
    kayitlar = Blogs.objects.all().order_by('-tarih').filter(yayinda=1).filter(arsiv=0)
    return render_to_response("blog.html", {'kayitlar':kayitlar},context_instance=RequestContext(request))

def blogsarsiv(request):
    arsivkayitlar = Blogs.objects.all().order_by('-tarih').filter(yayinda=1).filter(arsiv=1)
    return render_to_response("arsivblog.html", {'arsivkayitlar':arsivkayitlar},context_instance=RequestContext(request))

def blogsrss(request):
    kayitlarrss = Blogs.objects.all().order_by('-tarih').filter(yayinda=1).filter(arsiv=0)
    return render_to_response("blogrss.htm", {'kayitlarrss':kayitlarrss},context_instance=RequestContext(request))

def blogsarsivrss(request):
    arsivkayitlarrss = Blogs.objects.all().order_by('-tarih').filter(yayinda=1).filter(arsiv=1)
    return render_to_response("arsivblogrss.html", {'arsivkayitlar':arsivkayitlar},context_instance=RequestContext(request))


#def detay(request, slug):
 #   kayitlars, saybil=int()
  #  detay=kayitlars.get(slug=slug,)
   # saybil.update({'detay':detay})
    #return render_to_response("blogd.html",saybil)


def detay(request, slug):
    kayitlars, saybil=int()
    detay=kayitlars.get(slug=slug,)
    ipa = request.META['REMOTE_ADDR']
    saybil.update({'detay':detay,"ipa":ipa})
    if request.method == 'POST':
        form = Formu(request.POST)
        if form.is_valid():
            form.save()
            #return HttpResponseRedirect('/blogs/')
    else:
        form = Formu()
    return render_to_response('blogd.html', saybil)






def yorum(request, slug):
    altposts, altpagedata = init1()
    altkategoridetay = altposts.get(slug=slug,)
    altpagedata.update({'yorumdetay': yorumdetay})
    
   
def init1():
    altposts = Yorum.objects.all()
    altpagedata = {'post_list': altposts,}
    return altposts, altpagedata
	
def int():
    kayitlars = Blogs.objects.all()
    saybil = {'post_list': kayitlars,}
    return kayitlars, saybil
	

blogster/templates/anasayfa.html
{% extends "base.html" %}
{% block baslik %}

{%for bilgial in kayitlarana%}
{% autoescape off %}{{bilgial.konu}}{% endautoescape %}
{%endfor%}

{% endblock %}
{% block meta %}
<meta name="keywords" content="Freelance Web Designer, Freelance, Tasarım, Web Tasarımı, CSS, XHTML, Fireworks, Dreamweaver, Photoshop, Flash,  Banner, Kartvizit, Mailing Tasarımı, SEO" /> 
<meta name="description" content="Yasin YAMAN'nın freelance web tasarım alanındaki becerilerini duyurma çabası ile oluşturduğu kişisel site." />
{% endblock %}

{% block main %}

{%for bilgial in kayitlarana%}
{% autoescape off %}{{bilgial.icerik}}{% endautoescape %}
{%endfor%}

{% endblock %}

blogster/templates/arsivblog.html
{% extends "base.html" %}
{%load humanize%}
{% load pagination_tags %}
{% load markup %}
{% block meta %}
<meta name="keywords" content="{%for bilgial in kayitlar%}{{bilgial.slug}}, {%endfor%}" /> 
<meta name="description" content="Yasin YAMAN'nın freelance web tasarım alanındaki becerilerini duyurma çabası ile oluşturduğu kişisel MiniBlok'u." />

{% endblock %}
{% block baslik %}
MiniBlog
{% endblock %}
{% block main %}
<div class="blog"><h3><a href="/blogs"><img src="/static/blogb.png" border="0" /></a>  <a href="/arsivblogs"><img src="/static/arsivb.png" border="0" /></a></h3></div>
<table width="%100" border="0" cellpadding="0" cellspacing="0">
{%autopaginate arsivkayitlar 20 %}
{%for bilgial in arsivkayitlar%}
  <tr>
    <td height="25" colspan="3" valign="bottom" bgcolor="#f0f0f0"><h3 class="style2" style=" color: #666699;"><a href="/blogs/{{bilgial.slug}}">{{bilgial.konu|textile|safe}}</a></h3></td>
  </tr>

 <tr>
    <td width="447" height="27" bgcolor="#F3F3F3"><strong>Yayin Tarihi:</strong> {{bilgial.tarih}} </td>
    <td width="667" bgcolor="#F3F3F3"><strong>Ekleye:</strong> {{bilgial.user}}</td>
    <td width="163" bgcolor="#F3F3F3">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><p></td>
  </tr>
  {%endfor%}
</table>
{% paginate %}
{% endblock %}

blogster/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>.:: Yasin YAMAN  ::  Freelancer Web Designer // Freelance  Web Tasarımcı // {% block baslik %}{% endblock %} ::.</title>
{% block meta %}{% endblock %}
<meta name="robots" content="INDEX,FOLLOW" /> 
<meta name="googlebot" content="NOODP" /> 
<meta name="revisit-after" content="1 Days" /> 
<meta name="rating" content="General" /> 
<meta name="distribution" content="GLOBAL" /> 
<meta name="copyright" content="www.yasinyaman.com" />
<meta name="google-site-verification" content="gSadjTBOCdXCu0Bv0vOH4OJpmUvvzQ4OZmiDFUZX0Ww" />
<link rel="alternate" type="application/rss+xml" title="yasinyaman.com Mini Blog RSS Feed" href="/blogsrss/"/>
<link rel="Shortcut Icon" href="/static/mascot.ico"></link>
<link href="/static/stil.css" rel="stylesheet" type="text/css" />

{% block css %}{% endblock %}
{% block javasc %}{% endblock %}

<style type="text/css">
<!--
.style1 {font-size: 16px}
-->
</style>
</head>

<body>
<div class="page-body">
<table width="996" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
<td height="86" colspan="3" class="banner_" style="border-bottom:#666 thin"><a href="/anasayfa/" title="www.yasinyaman.com"><img src="/static/images/log2.png"/></a></td>
  </tr>
<tr>
<td colspan="3" >&nbsp;</td>
 </tr>
  <tr>
    <td width="786" height="%100" class="metin"><table width="785" height="%100" border="0" cellpadding="0" cellspacing="0">
      <tr valign="bottom">
        <td height="%100" colspan="6"  valign="top" {% block clas %}{% endblock %}>
{% block main %}{% endblock %}
</td>
      </tr>
    </table></td>
    <td width="10" class="metin">&nbsp;</td>
    <td width="200" align="left" valign="top"><table width="200" border="0" cellpadding="0" cellspacing="0" >
      <tr>
        <td><a href="/anasayfa/" title="Anasayfa"><img src="/static/images/ana.png" width="158" height="50" alt="Anasayfa" /></a></span></td>
      </tr>
      <tr>
      <td >..................................................................</td>
      </tr>
      <tr valign="bottom">
        <td height="46"><a href="/hakkimda/" title="Hakkımda"><img src="/static/images/hakkimda.png" width="158" height="39" alt="hakkımda" /></a></td>
      </tr>
      <tr>
        <td>..................................................................</td>
      </tr>
      <tr valign="bottom">
        <td height="41"><a href="/portfolyo/" title="Portfolyo"><img src="/static/images/portfolyo.png" width="158" height="35" /></a></td>
      </tr>
      
      <tr>
        <td >..................................................................</td>
      </tr>
      <tr>
        <td height="45"><a href="/iletisim/" title="İletişim"><img src="/static/images/iletisim.png" width="137" height="34" /></a></td>
      </tr>
      <tr valign="top">
        <td>..................................................................</td>
      </tr>
      <tr>
        <td height="46"><a href="/siparis/" title="Sipariş Formu"><img src="/static/images/siparis_form.png"/></a></td>
      </tr>
      <tr valign="top">
        <td>..................................................................</td>
      </tr>
      <tr>
        <td height="46"><a href="/blogs/" title="MiniBlog"><img src="/static/images/blog.png"/></a></td>
      </tr>
      <tr valign="top">
        <td>..................................................................</td>
      </tr>
	        <tr>
        <td height="46"><a href="/ttk_internet_sitesi" title="Yeni Türk Ticaret Kanunu ile web sitesi zorunluluğu getirildi."><img src="/static/images/ttk.png"/></a><br /><center><img src="/static/531993.png"/></center></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="13" colspan="3"></td>
  </tr>
  <tr >
    <td height="13" colspan="3" align="left" ><table width="996" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="441" title="Yasin YAMAN Freelancer Web Tasarım & Programlama">© 2010 The Web Design & Programing Yasin YAMAN</td>
        <td width="555" align="right"><a href="/anasayfa/" title="Anasayfa">anasayfa</a> / <a href="/hakkimda/" title="Hakkımda"> hakkımda</a> / <a href="/portfolyo/" title="Portfolyo">portfolyo</a> / <a href="/iletisim/" title="İletişim"> iletişim</a> / <a href="/siparis/" title="siparis formu">siparis formu</a> / <a href="/blogs/" title="MiniBlog">mini blog</a></td>
      </tr>
    </table></td>
  </tr>
  <tr valign="top" >
    <td height="2" colspan="3">..........................................................................................................................................................................................................................................................................................................................................</td>
  </tr>
   <tr valign="top" >
   <td height="2" colspan="3"><center>
     <table width="967" height="19" border="0"  cellpadding="0" cellspacing="0">
       <tr>
         <td>&nbsp;</td>
         <td>&nbsp;</td>
         <td width="468" rowspan="2" align="center" >
<a href="http://www.yazki.com" target="_blank" title="www.yazki.com - Açık Kaynak Kodlu Teknolojiciler Topluluğu"><img src="/static/images/yazki.png"/></a>
<a href="http://www.debian.org" target="_blank" title="Debian - The Universal Operating System"><img src="/static/images/debian.jpg"/></a>
<a href="http://www.djangoproject.com" target="_blank" title="Django"><img src="/static/images/django.png"/></a>
<a href="http://www.python.org" target="_blank" title="Python"><img src="/static/images/python.png"/></a>
<a href="http://www.iglon.com" target="_blank" title="Iglon Web Studio"><img src="/static/images/iglon.png"/></a>

</td>
         <td width="90" rowspan="2" align="center"> <img src="/static/lkd.png" /></td>
       </tr>
       <tr>
         <td width="152"><h3 title="Sosyal ağlara eklemek için butonları kullan">Sosyal Ağlara Ekle:</h3> </td>
         <td width="257"><a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=http://www.yasinyaman.com" title="Linkedin'e ekle"><img src="/static/images/linkedin_64x64.png" width="64" height="64" /></a><a href="http://www.google.com/bookmarks/mark?op=edit&amp;bkmk=http://www.yasinyaman.com" title="Google'a ekle"><img src="/static/images/google_64x64.png" width="64" height="64" /></a><a href="http://www.facebook.com/share.php?u=http://www.yasinyaman.com" title="Facebook'ta Paylaş"><img src="/static/images/facebook_64x64.png" width="64" height="64" /></a><a href="http://twitter.com/home?status=http://www.yasinyaman.com" title="Twitter'de yayınla"><img src="/static/images/twitter_64x64.png" width="64" height="64" /></a></td>
         </tr>
       </table>
   </center></td>
  </tr>
</table>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-10798685-1");
pageTracker._trackPageview();
} catch(err) {}
</script>

</body>
</html>

blogster/templates/blog.html
{% extends "base.html" %}
{%load humanize%}
{% load pagination_tags %}
{% load markup %}
{% block meta %}
<meta name="keywords" content="{%for bilgial in kayitlar%}{{bilgial.slug}}, {%endfor%}" /> 
<meta name="description" content="Yasin YAMAN'nın freelance web tasarım alanındaki becerilerini duyurma çabası ile oluşturduğu kişisel MiniBlok'u." />
<style>

</style>
{% endblock %}
{% block baslik %}
MiniBlog
{% endblock %}
{% block main %}
<div class="blog"><h3><a href="/blogs"><img src="/static/blogb.png" border="0" /></a> <a href="/arsivblogs"><img src="/static/arsivb.png" border="0" /></a></h3></div>
<table width="%100" border="0" cellpadding="0" cellspacing="0">
{%autopaginate kayitlar 10 %}
{%for bilgial in kayitlar%}
  <tr>
    <td height="25" colspan="3" valign="bottom" bgcolor="#f0f0f0"><h3 class="style2" style=" color: #666699;">{{bilgial.konu}}</h3></td>
  </tr>
  <tr>
    <td height="44" colspan="3" valign="middle" bgcolor="#f9f9f9"><div align="justify" style="border-collapse: collapse; font-family: Arial,sans-serif; font-size: small; color: #000000">{{bilgial.icerikozet|textile|safe}}</div>
<h3>
<a href="/blogs/{{bilgial.slug}}"><u>(Devamini Oku)</u><a/></h3></td>
  </tr>
 <tr>
    <td width="447" height="27" bgcolor="#F3F3F3"><strong>Yayin Tarihi:</strong> {{bilgial.tarih}} </td>
    <td width="667" bgcolor="#F3F3F3"><strong>Ekleye:</strong> {{bilgial.user}}</td>
    <td width="163" bgcolor="#F3F3F3">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><p></td>
  </tr>
  {%endfor%}
</table>
<strong>{% paginate %}</strong>
{% endblock %}

blogster/templates/blogd.html
{% extends "base.html" %}
{%load humanize%}
{% load markup %}

{% block meta %}
<meta name="keywords" content="{{detay.konu}}" /> 
<meta name="description" content="{{detay.konu}}" />
{% endblock %}
{% block baslik %}
MiniBlog - {{detay.konu}}
{% endblock %}
{% block css %}
<style> 

font-family:Verdana, Arial, Helvetica, sans-serif;
font-size:11px;}
.genislik {margin:auto;}


</style> 
{% endblock %}
{% block javasc %}
<SCRIPT language=JavaScript> 
function regKontrol(pattern, value) 
{ 
r = new RegExp(pattern, "g"); 
return r.test(value); 
} 
 
function formKontrol(form) 
{ 
patternEposta = "^"+"([abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0-9_\.\-]+)"+"@"+"([abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0-9_\.\-]+)"+"[\.]"+"([abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0-9_\.\-]+)"+"$"; 
 
if ( !regKontrol(patternEposta,form.email.value)) 
{ 
alert("Lütfen Doğru Bir E-posta Adresi Giriniz."); 
form.email.value=""; 
form.email.focus(); 
return false; 
} 
return true; 
} 
</SCRIPT> 
<script type="text/javascript" src="/static/md5_has_create.js"></script> 
{% endblock %}
{% block main %}
<table width="%100" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="25" colspan="4" valign="bottom" bgcolor="#f0f0f0"><h3 class="style2" style=" color: #666699;">{{detay.konu}}</h3></td>
  </tr>
  <tr>
    <td height="44" colspan="4" valign="middle" bgcolor="#f9f9f9"><div align="justify" style="border-collapse: collapse; font-family: Arial,sans-serif; font-size: small; color: #000000">{{detay.icerik|safe}}</div></td>
  </tr>
  <tr>
    <td width="447" height="27" bgcolor="#F3F3F3"><strong>Yayin Tarihi:</strong> {{detay.tarih}} </td>
    <td width="307" bgcolor="#F3F3F3"><strong>Ekleye:</strong> {{detay.user}}</td>
    <td width="106" bgcolor="#F3F3F3"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a></td>
    <td  bgcolor="#F3F3F3">
<a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;username=xa-4b67040a366222fd"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=xa-4b67040a366222fd"></script></td>
  </tr>
  <tr>
    <td colspan="4">
<iframe src="http://www.facebook.com/plugins/like.php?href=http://www.yasinyaman.com/blogs/{{detay.slug}}&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;font=verdana&amp;colorscheme=dark&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
</td>
  </tr>
</table>
<br/>
<h2>"{{detay.konu}}" İle İlgili Yorumlar:</h2>
{%for yorum in detay.yorum_set.all%}

<hr>
<p>
<table  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td rowspan="3" height="51px" width="51px"><img src="http://www.gravatar.com/avatar/{{yorum.smd5}}.png" width="50" height="50"/></td>
    <td>{{yorum.tarih}}</td>
  </tr>
  <tr>
    <td><strong style="font-size:small;">{{yorum.isim}} Diyor ki;</strong></td>
  </tr>
</table>
<br/><div align="justify" style="border-collapse: collapse; font-family: Arial,sans-serif; font-size: small; color: #777777">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{yorum.mesaj}}</div><p/>

{%endfor%}
<br />
<hr>
<h2>Yorum Yaz:</h2>
<form method="post" action="" onsubmit="return formKontrol(this);" style="width:610px;"> 
<input name="konu"  type="hidden" value="{{detay.id}}" id="id_konu" />
<input name="ip"  type="hidden" value="{{ipa}}" id="id_ip" />
<input name="smd5"  type="hidden" id="id_smd5" />
<label><input type="text" name="isim" id="id_isim"  title="Isim / Nick" style=" border:none; width:300px; border:solid; border-width:thin; border-color:#999999;" />&nbsp;&nbsp;<strong>İsim</strong></label><br/>
<label><input type="text" name="email" id="id_email"  style="border:none; width:300px;border:solid;border-width:thin;  border-color:#999999;"/>&nbsp;&nbsp;<strong>E Posta (Yayınlanmaz)</strong></label> 
<br /> 
<textarea id="id_mesaj"  name="mesaj" placeholder="Mesaj"  style="width:600px; height:70px; border:solid; border-width:thin; border-color:#999999;" ></textarea> 
<br /> <div align="left"> 
<input  value="Gönder" style="border:solid; border-width:thin; border-color:#999999;" type="submit"  onclick="smd5.value = hex_md5(email.value)"/><div> 
 </form><p> 

{% endblock %}

blogster/templates/blogrss.htm
{%load humanize%}
{% load markup %}
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/"> 
	<channel> 
		<title>yasinyaman.com</title> 
		<link>http://yasinyaman.com/blogs/</link> 
		<description>Yasin MiniBlok'u</description> 
		<language>tr</language> 
		<generator>Yasin YAMAN Mini Blog</generator> 
		<ttl>60</ttl> 
		<image> 
			<url>http://forum.shiftdelete.net/sd/misc/rss.jpg</url> 
			<title>SDN</title> 
			<link>yasinyaman.com</link> 
		</image> 
{%for bilgial in kayitlarrss%}
<item> 
<title>{{bilgial.konu}}</title> 
<link>http://www.yasinyaman.com/blogs/{{bilgial.slug}}</link> 
<pubDate>{{bilgial.tarih}}</pubDate> 
<content:encoded><![CDATA[ {{bilgial.icerikozet|textile|safe}} ]]></content:encoded> 
<dc:creator>{{bilgial.user}}</dc:creator> 
<guid isPermaLink="true">http://www.yasinyaman.com/blogs/{{bilgial.slug}}</guid> 
</item> 
  {%endfor%}
</channel> 
</rss>

blogster/templates/yivitir.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{%for bilgial in kayitlar%}
{{bilgial.icerik}} <br/> {{bilgial.tarih}}
{%endfor%}